question_data = [
                     {"type": "boolean",
                      "difficulty": "easy",
                      "category": "General Knowledge",
                      "question": "Ping-Pong originated in England",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "The Sun rises from the North.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Pluto is a planet.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
                      "incorrect_answers": ["True"]}]
